name: todo
description: A simple todo app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  firebase_auth: ^3.4.1
  firebase_core: ^1.19.1
  firebase_database: ^9.0.18
  firebase_storage: ^10.3.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  go_router: ^4.1.0
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         style: italic
